#!/usr/bin/env lua5.4
-- Минимальная замена утилиты bin2c (SourceForge v1.1) на чистом Lua.
-- Поддерживает ровно ту форму вызова, что нужна codegen в bld.lua:
--   bin2c -t -d <header.h> -o <output.c> <input-file>
-- Воспроизводит формат вывода bin2c 1.1: массив байт, *_size, файловую
-- таблицу (-t). Имя символа выводится из строки пути аргумента: все
-- не [A-Za-z0-9] заменяются на '_'.

local function die(msg) io.stderr:write("bin2c.lua: " .. msg .. "\n"); os.exit(1) end

-- разбор аргументов
local header, output, want_table, input
local i = 1
while i <= #arg do
    local a = arg[i]
    if a == "-t" or a == "--table" then
        want_table = true
    elseif a == "-d" or a == "--header" then
        i = i + 1; header = arg[i]
    elseif a == "-o" or a == "--output" then
        i = i + 1; output = arg[i]
    elseif a:sub(1, 1) ~= "-" then
        input = a
    end
    i = i + 1
end
if not input then die("не задан входной файл") end
if not output then die("не задан -o <output>") end

-- символ из пути аргумента: не-алфанумерик -> '_'
local sym = input:gsub("[^%w]", "_")

-- читаем входные данные
local f = assert(io.open(input, "rb"))
local data = f:read("a"); f:close()
local size = #data

-- guard из имени header-файла: не-алфанумерик -> '_'
local guard = "__" .. (header and header:gsub("[^%w]", "_") or "data") .. "_included"

-- тело C-массива: 16 байт в строке, отступ 4 пробела, ", " разделитель
local function emit_array()
    local out, line = {}, {}
    for j = 1, size do
        line[#line + 1] = string.format("0x%02X", data:byte(j))
        if #line == 16 or j == size then
            out[#out + 1] = "    " .. table.concat(line, ", ") ..
                            (j == size and "" or ",")
            line = {}
        end
    end
    return table.concat(out, "\n")
end

-- запись .h
if header then
    local h = assert(io.open(header, "w"))
    h:write("/* Generated by bin2c, do not edit manually */\n")
    h:write("#ifndef " .. guard .. "\n#define " .. guard .. "\n\n")
    h:write("/* Contents of file " .. input .. " */\n")
    h:write("extern const long int " .. sym .. "_size;\n")
    h:write("extern const unsigned char " .. sym .. "[" .. size .. "];\n\n")
    if want_table then
        h:write("/* File table comprising original file name, address and size */\n")
        h:write("typedef struct {\n\tchar *entryName;\n\tconst char *data;\n\tlong int size;\n} TFileTableEntry;\n\n")
        h:write("extern const unsigned int fileTableSize;\n")
        h:write("extern const TFileTableEntry fileTable[];\n")
    end
    h:write("\n#endif    /* " .. guard .. " */\n")
    h:close()
end

-- запись .c
local c = assert(io.open(output, "w"))
c:write("/* Generated by bin2c, do not edit manually */\n\n")
if header then c:write('#include "' .. header .. '"\n\n') end
c:write("/* Contents of file " .. input .. " */\n")
c:write("const long int " .. sym .. "_size = " .. size .. ";\n")
c:write("const unsigned char " .. sym .. "[" .. size .. "] = {\n")
c:write(emit_array())
c:write("\n};\n")
if want_table then
    c:write("\nconst TFileTableEntry fileTable[] = {\n")
    c:write('\t{"' .. input .. '", ' .. sym .. ", " .. size .. "}\n")
    c:write("};\n")
    c:write("const unsigned int fileTableSize = 1;\n")
end
c:close()
