#!/usr/bin/env bash

# Печатать выполняемую команду оболочки
#set -x
# Прерывать выполнение сценария при ошибке
set -e

# Проверка на наличие CAUSTIC_PATH
if [ -z "$CAUSTIC_PATH" ]; then
  echo "Ошибка: переменная окружения CAUSTIC_PATH не установлена."
  exit 1
fi

# Получение переменных от luarocks
LUA_VER="5.4"
LUA_PATH_STR=$(luarocks --local --lua-version=$LUA_VER path --lr-path)
LUA_CPATH_STR=$(luarocks --local --lua-version=$LUA_VER path --lr-cpath)
LUAROCKS_BIN=$(luarocks --local --lua-version=$LUA_VER path --lr-bin)

# Добавляем tl_dst/?.lua в путь
CAUSTIC_MODULE_PATH="$CAUSTIC_PATH/tl_dst/?.lua"

#echo $CAUSTIC_MODULE_PATH

# Объединение путей
export LUA_PATH="$LUA_PATH_STR;$CAUSTIC_MODULE_PATH"
export LUA_CPATH="$LUA_CPATH_STR"
export PATH="$LUAROCKS_BIN:$PATH"

# Запуск Caustic
ASAN_OPTIONS=verify_asan_link_order=0 lua5.4 "$CAUSTIC_PATH/tl_dst/caustic.lua" "$@"
