return {
    "/home/nagolove/caustic-test-mm_arena",
    "/home/nagolove/caustic-test-qtree",
    "/home/nagolove/caustic-test-b2",
    "/home/nagolove/caustic-test-common",
    "/home/nagolove/caustic-test-ecs",
    "/home/nagolove/caustic-test-ecs-2",
    "/home/nagolove/caustic-test-htable",
    "/home/nagolove/caustic-test-lua-tools",
    "/home/nagolove/caustic-test-metaloader",
    "/home/nagolove/caustic-test-pallete",
    "/home/nagolove/caustic-test-render",
    --"/home/nagolove/caustic-test-set",
    --"/home/nagolove/caustic-test-strset",
}
