#pragma once 

#include "koh_adsr.h"
#include "koh_array.h"
#include "koh_cammode.h"
#include "koh_common.h"
#include "koh_console.h"
#include "koh_das.h"
#include "koh_das_interface.h"
#include "koh_das_mt.h"
#include "koh_destral_ecs.h"
#include "koh_dev_draw.h"
#include "koh_ecs.h"
#include "koh_genann_view.h"
#include "koh_hashers.h"
#include "koh_height_color.h"
#include "koh_hotkey.h"
#include "koh_iface.h"
#include "koh_inotifier.h"
#include "koh_input.h"
#include "koh_layer.h"
#include "koh_logger.h"
#include "koh_lua_tools.h"
#include "koh_menu.h"
#include "koh_music.h"
#include "koh_net.h"
#include "koh_object.h"
#include "koh_outline.h"
#include "koh_paragraph.h"
#include "koh_path.h"
#include "koh_pool.h"
#include "koh_rand.h"
#include "koh_reasings.h"
#include "koh_render.h"
#include "koh_resource.h"
#include "koh_routine.h"
#include "koh_script.h"
#include "koh_sfx.h"
#include "koh_stages.h"
#include "koh_strset.h"
#include "koh_tabe.h"
#include "koh_table.h"
#include "koh_team.h"
#include "koh_timer.h"
#include "koh_wfc.h"

/*
#include "koh_stage_adsr.h"
#include "koh_stage_bzr_curve.h"
#include "koh_stage_ecs.h"
#include "koh_stage_empty.h"
#include "koh_stage_fight_menu_paste.h"
#include "koh_stage_fight_menu_player.h"
#include "koh_stage_heightcolor.h"
#include "koh_stage_iface.h"
#include "koh_stage_immediate.h"
#include "koh_stage_inputbuf.h"
#include "koh_stage_orandom.h"
#include "koh_stage_paragraph.h"
#include "koh_stage_path.h"
#include "koh_stage_rand.h"
#include "koh_stage_terrain2.h"
#include "koh_stage_terrain.h"
#include "koh_stage_timers.h"
#include "koh_stage_tst_menu.h"
*/


