/* Generated by bin2c, do not edit manually */
#ifndef __koh_lua_tabular_h_included
#define __koh_lua_tabular_h_included

/* Contents of file ../tl_dst/tabular.lua */
extern const long int ___tl_dst_tabular_lua_size;
extern const unsigned char ___tl_dst_tabular_lua[6893];

/* File table comprising original file name, address and size */
typedef struct {
	char *entryName;
	const char *data;
	long int size;
} TFileTableEntry;

extern const unsigned int fileTableSize;
extern const TFileTableEntry fileTable[];

#endif    /* __koh_lua_tabular_h_included */
