#pragma once

const char *fs_code_sdf =
"#version 330\n"
"// Input vertex attributes (from vertex shader)\n"
"in vec2 fragTexCoord;\n"
"in vec4 fragColor;\n"
"// Input uniform values\n"
"uniform sampler2D texture0;\n"
"uniform vec4 colDiffuse;\n"
"// Обводка текста: цвет и ширина (в единицах SDF-дистанции, ~0..0.5)\n"
"uniform vec4 outlineColor;\n"
"uniform float outlineWidth;\n"
"// Output fragment color\n"
"out vec4 finalColor;\n"
"void main()\n"
"{\n"
"   // Знаковая дистанция до края глифа (положительная внутри)\n"
"   float distanceFromOutline = texture(texture0, fragTexCoord).a - 0.5;\n"
"   float distanceChangePerFragment = length(vec2(dFdx(distanceFromOutline), dFdy(distanceFromOutline)));\n"
"   float fillAlpha = smoothstep(-distanceChangePerFragment, distanceChangePerFragment, distanceFromOutline);\n"
"   if (outlineWidth <= 0.0) {\n"
"       finalColor = vec4(fragColor.rgb, fragColor.a * fillAlpha);\n"
"   } else {\n"
"       // край обводки не должен доставать до углов квада глифа (zoom-out)\n"
"       float aaOuter = min(distanceChangePerFragment, max(0.0, 0.5 - outlineWidth - 0.03));\n"
"       float outerAlpha = smoothstep(-aaOuter, aaOuter, distanceFromOutline + outlineWidth);\n"
"       vec3 rgb = mix(outlineColor.rgb, fragColor.rgb, fillAlpha);\n"
"       float a = mix(outlineColor.a, fragColor.a, fillAlpha) * outerAlpha;\n"
"       finalColor = vec4(rgb, a);\n"
"   }\n"
"}\n"
;
